/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    AppSidebar: typeof import('./../components/AppSidebar.vue')['default']
    ClientOnly: typeof import('./../components/ClientOnly.vue')['default']
    LanguageSwitcher: typeof import('./../components/LanguageSwitcher.vue')['default']
    NuxtLink: typeof import('./../components/NuxtLink.vue')['default']
    RichTextField: typeof import('./../components/editor/RichTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMenu: typeof import('./../components/UserMenu.vue')['default']
  }
}
